trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: react-app
  dockerfilePath: Dockerfile
  tag: $(Build.BuildId)

steps:

- task: Docker@2
  displayName: Build and Push to ACR
  inputs:
    command: buildAndPush
    containerRegistry: 'sc-jkaks-acr'
    repository: '$(imageRepository)'
    dockerfile: '$(dockerfilePath)'
    tags: |
      $(tag)
      latest